# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f ci-cd-requirements.txt ]; then pip install -r ci-cd-requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --show-source --statistics ./assignments
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 ./assignments --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check types with mypy
      run: |
        mypy --strict --allow-untyped-decorators --ignore-missing-imports ./assignments/A3-unittesting/morsecodepalindromes/
        mypy --strict --allow-untyped-decorators --ignore-missing-imports ./assignments/A4-Mocking_Hypothesis/titlecost/
        mypy --strict --allow-untyped-decorators --ignore-missing-imports ./assignments/A5-API/
        mypy --strict --allow-untyped-decorators --ignore-missing-imports ./assignments/A6-inheritance/statistics/
        mypy --strict --allow-untyped-decorators --ignore-missing-imports ./assignments/A7-abc/cups/
    - name: Test with pytest
      run: |
        pytest --verbose ./assignments/A3-unittesting/morsecodepalindromes/tests 
        pytest --verbose ./assignments/A4-Mocking_Hypothesis/titlecost/tests
        pytest --verbose ./assignments/A6-inheritance/statistics/tests
        pytest --verbose ./assignments/A7-abc/cups/tests
    - name: Coverage report
      run: |
        pytest --cov-report=xml:./assignments/A3-unittesting/morsecodepalindromes/coverage.xml --cov=./assignments/A3-unittesting/morsecodepalindromes/ ./assignments/A3-unittesting/morsecodepalindromes/tests
        pytest --cov-report=xml:./assignments/A4-Mocking_Hypothesis/titlecost/coverage.xml --cov=./assignments/A4-Mocking_Hypothesis/titlecost/ ./assignments/A4-Mocking_Hypothesis/titlecost/tests
    - name: Uploading Coverage Reports
      uses: codecov/codecov-action@v4.0.1
      with:
        fail_ci_if_error: false
        files: ./assignments/A3-unittesting/morsecodepalindromes/coverage.xml,./assignments/A4-Mocking_Hypothesis/titlecost/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: LobotomyTerror/OOP-dfishbein
        
        